<?php
/** @var \MaxServ\ProductGallery\Block\Catalog\Product\View\Gallery $block */

/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getProduct();

$baseImage = $block->getImage($product, 'product_page_image_medium');
$galleryImages = $block->getGalleryImages();
?>
<div>
    <div class="productGallery" data-mage-init='{"productGallery":{}}'>
        <div class="productGallery-images">
            <?php foreach ($galleryImages as $galleryImage): ?>
                <a class="productGallery-image" href="#">
                    <img src="<?php echo $galleryImage->getMediumImageUrl(); ?>" class="productGallery-image-medium" />
                    <img src="<?php echo $galleryImage->getLargeImageUrl(); ?>" class="productGallery-image-large" />
                </a>
            <?php endforeach; ?>
        </div>
        <div class="productGallery-navigation">
            <div class="productGallery-thumbnails">
                <?php $i = 0; ?>
                <?php foreach ($galleryImages as $galleryImage): ?>
                    <a class="productGallery-thumbnail" href="#" data-index="<?php echo $i; ?>">
                        <img src="<?php echo $galleryImage->getSmallImageUrl(); ?>"/>
                    </a>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
<script type="text/template" id="productGallery-lightbox-template">
    <div class="productGallery-lightbox">
        <a href="#" class="productGallery-lightbox-close">
            <svg viewbox="0 0 40 40">
                <path class="close-x" d="M 10,10 L 30,30 M 30,10 L 10,30" />
            </svg>
        </a>
    </div>
</script>
